

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AI_API_KEY=${AI_API_KEY}
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=sqlite:///game.db
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: